application: conversations-app
version: 1
runtime: python27
api_version: 1
threadsafe: no

#inbound_services:
#- mail

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: favicon.ico

- url: /static
  static_dir: static

- url: /_ah/mail/.+
  script: handlers.inmail.app

- url: /api/.+
  script: handlers.api.app

- url: .*
  script: handlers.web.app

libraries:
- name: webapp2
  version: "2.5.1"
